### ISSUE TITLE
firefox can't get response from https://download.dnscrypt.org/dnscrypt-proxy/

### ISSUE THREAD

**Issue by CNMan** [jedisct1/dnscrypt-proxy#544]
firefox esr 45.6.0
![2017-01-05_153903](https://cloud.githubusercontent.com/assets/8692234/21672409/638a4252-d35d-11e6-8b7b-b9f2b3bf26d1.png)

but chrome works fine
![2017-01-05_154259](https://cloud.githubusercontent.com/assets/8692234/21672448/ad35e64a-d35d-11e6-8507-fb563fb62b95.png)

**Comment by jedisct1** [comment]
Old browser that doesn't support TLS 1.2. Sorry, I'm not going to support that in 2017.

**Comment by CNMan** [comment]
firefox esr 45.6.0 supports TLS 1.2
![2017-01-05_164717](https://cloud.githubusercontent.com/assets/8692234/21673977/aa63a53e-d366-11e6-9c30-5587fae538a0.png)

**Comment by jedisct1** [comment]
Indeed. What it doesn't support is AES256.

AES128 was added to the cipher suite. It should work now. But supporting old software is not fun.

**Comment by CNMan** [comment]
still don't work
![2017-01-05_172010](https://cloud.githubusercontent.com/assets/8692234/21675125/8d4166e4-d36b-11e6-8b29-10dc4d4b4562.png)

**Comment by licaon-kter** [comment]
Yep, #386 :(

**Comment by CNMan** [comment]
works now,thank you:)
